name: TRACE Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install git+https://github.com/transparency-certified/trace-prototype
      - name: Submit to TRACE System
        run: |
          trace-poc submit --entrypoint "run.sh" --container-user rstudio --target-repo-dir "/home/rstudio" --trace-server https://server.trace-poc.xyz .
